name: golden_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  barcode_scan: any
  geolocator: ^6.0.0
  pattern_formatter: ^1.0.2
  firebase_messaging: ^7.0.0
  flutter_launcher_icons: ^0.7.5
  flutter_screenutil: ^2.3.0
  shared_preferences: ^0.5.10
  validators: ^2.0.0+1
  search_widget: ^1.0.2
  mask_text_input_formatter: ^1.0.7
  autocomplete_textfield: ^1.6.4
  intl: ^0.16.0
  equatable: ^1.2.4
  cupertino_icons: ^0.1.3
  floor: ^0.14.0
  meta: ^1.1.8
  uuid: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.14.0
  build_runner: ^1.10.2
  mockito: ^4.1.1

flutter_icons:
  image_path: 'images/icon.png'
  android: true
  ios: true

flutter:
  assets:
    - images/logo.png
    - images/app_icon.png
    - images/icon.png
  uses-material-design: true